
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nyan Lin Htun
 */
public class Custom_Panel2 extends javax.swing.JPanel {
    private ImageIcon Image;
    /**
     * Creates new form Custom_Panel2
     */
    public Custom_Panel2() {
        initComponents();
    }
    
     public void setImage(ImageIcon _Image){
        this.Image=_Image;
    }
    public ImageIcon getImage(){
        return getResizeImage(this.Image);
    }
     public void displayView(){
         lblimage.setIcon(getImage());
    }

     public ImageIcon getResizeImage(ImageIcon image){
       final int WIDTH = 150;
       final int HEIGHT = 150;
       
       java.awt.Image img = image.getImage();
         
        java.awt.Image newImg=img.getScaledInstance(WIDTH,HEIGHT,java.awt.Image.SCALE_SMOOTH);
        ImageIcon new_image=new ImageIcon(newImg);
        System.out.println(new_image.getIconWidth());
        
        return new_image;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataflowImage = new javax.swing.JPanel();
        lblimage = new javax.swing.JLabel();

        javax.swing.GroupLayout DataflowImageLayout = new javax.swing.GroupLayout(DataflowImage);
        DataflowImage.setLayout(DataflowImageLayout);
        DataflowImageLayout.setHorizontalGroup(
            DataflowImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimage, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        DataflowImageLayout.setVerticalGroup(
            DataflowImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimage, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DataflowImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DataflowImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataflowImage;
    private javax.swing.JLabel lblimage;
    // End of variables declaration//GEN-END:variables
}
