 
import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection; 
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nyan Lin Htun
 */
public class PhoneList extends javax.swing.JFrame {
     static Connection conn;
     String username="";
	String password="";
	ResultSet rs;
	Statement stmt;
	String sql;
        PreparedStatement ps;

    /**
     * Creates new form PhoneList
     */
        Custom_Panel panel;
        final int COlUMN = 1; //row is dynamic
         final String Storage_Path="Resources/images/";
         public String model1;
    public PhoneList() throws SQLException, IOException {
        initComponents();
        

    }
    public PhoneList(String arg) throws SQLException, IOException{
        initComponents();
        
        //System.out.println(arg);
        Display(arg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataFlowPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(3, 169, 244));

        jPanel2.setBackground(new java.awt.Color(224, 247, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setAutoscrolls(true);

        jScrollPane1.setAutoscrolls(true);

        DataFlowPanel.setLayout(new java.awt.GridLayout(10, 1));
        jScrollPane1.setViewportView(DataFlowPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhoneList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhoneList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhoneList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhoneList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    try {
                        new PhoneList().setVisible(true);
                    } catch (IOException ex) {
                        Logger.getLogger(PhoneList.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(PhoneList.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    public static void LoadDriver() throws SQLException{
    String db="jdbc:ucanaccess://Resources/DB/Mobile Phone.accdb";
         
             conn=DriverManager.getConnection(db,"","");
             System.out.println("Connected Database");
    }
    void Display(String Brand) throws SQLException, IOException{
        LoadDriver();
        
         try {
             stmt = conn.createStatement ();
             sql="select count(*) as rowcount from Phones where Brand='"+Brand+"'";
             rs=stmt.executeQuery(sql);
             System.out.println(Brand);
             rs.next();
             int Total_Rows=rs.getInt("rowcount");//total row
             DataFlowPanel.setLayout(new GridLayout(Total_Rows,COlUMN));
         } catch (SQLException ex) {
             Logger.getLogger(PhoneList.class.getName()).log(Level.SEVERE, null, ex);
         }finally{
             stmt.close();
         }
        
         try {
             
             stmt = conn.createStatement ();
             sql = "select * from Phones where Brand='"+Brand+"'";
             rs = stmt.executeQuery (sql);
             while(rs.next()){
                 String model=rs.getString("Model");
                 int price = rs.getInt("Price");
                 
                 String image_path=Storage_Path+model+".jpg";
                 File file = new File(image_path);
                 BufferedImage image = ImageIO.read(file);
                 ImageIcon img = new ImageIcon(image);

                 panel=new Custom_Panel();
                 panel.setModel(model);
                 panel.setPrice(price);                    
                 panel.setImage(img);
                 panel.displayView();
                 DataFlowPanel.add(panel);
             }

         } catch (SQLException ex) {
             Logger.getLogger(PhoneList.class.getName()).log(Level.SEVERE, null, ex);
         }finally{
             try {
                 stmt.close();
                 conn.close();
             } catch (SQLException ex) {
                 Logger.getLogger(PhoneList.class.getName()).log(Level.SEVERE, null, ex);
             }
             
         }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataFlowPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
